language: node_js
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.npm
node_js:
  - "12"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm i -g npm

install:
  - npm install

script:
- npm run lint
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- npm run bundlesize

# e2e ssr
- npm run build:ssr
- npm run e2e:ssr
