sudo: required

dist: bionic

language: node_js

node_js:
  - 12

python:
  - "3.7"

services:
  - docker
  - xvfb

before_install:
  - if [[ $TRAVIS_BRANCH == "testing" || $TRAVIS_BRANCH == "testing" ]]
    then
      export E2E_TAG="$TRAVIS_BRANCH"
    else
      export E2E_TAG="latest"
    fi

install:
  - npm install

addons:
  chrome: stable

script:
  - npm run ci

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(testing|staging|master)$

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
