sudo: required

dist: trusty

language: node_js

node_js:
  - 12

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

addons:
  chrome: stable

script:
  - npm run ci

before_deploy:
  - docker build -t sartography/cr-connect-frontend .

deploy:
  provider: script
  script: bash ./docker/docker_push.sh
  on:
    branch: master
