language: node_js
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.npm
node_js:
  - "12"

before_install:
  - npm i -g npm

install:
  - npm ci

script:
- npm run lint
- if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then commitlint-travis; fi
- npm run test
- npm run bundlesize

# e2e ssr
- npm run build:ssr
- npm run e2e:ssr

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy; fi
  - if [ -n "$TRAVIS_TAG" ]; then npm run github-release; fi

addons:
  chrome: stable
