sudo: required

dist: bionic

language: node_js

node_js:
  - 12

python:
  - "3.7"

services:
  - docker
  - xvfb

install:
  - npm install

env:
  - E2E_TAG=$((("$TRAVIS_BRANCH" == "testing" || "$TRAVIS_BRANCH" == "testing") && echo "$TRAVIS_BRANCH") || echo "latest")

addons:
  chrome: stable

script:
  - npm run ci

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(testing|staging|master)$

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
