sudo: required

dist: bionic

language: node_js

node_js:
  - 12

python:
  - "3.7"

services:
  - docker
  - xvfb

before_install:
  - |
    if [[ $TRAVIS_BRANCH =~ ^(dev|testing|demo|training|staging|rrt\/.*)$ ]]; then
      export E2E_TAG="${TRAVIS_BRANCH//\//_}"
    else
      export E2E_TAG="latest"
    fi
    echo "E2E_TAG = $E2E_TAG"

install:
  - npm install

addons:
  chrome: stable

script:
  - export BASE_HREF="/"
  - npm run ci

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(dev|testing|demo|training|staging|master|rrt\/.*)$

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
