sudo: required

dist: bionic

language: node_js

node_js:
  - 12

python:
  - "3.7"

services:
  - docker

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

addons:
  chrome: stable

script:
  - npm run ci

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
