sudo: required

dist: trusty

language: node_js

node_js:
  - 12

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

addons:
  chrome: stable

script:
  - npm run ci

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
